[Appearance]
style=gtk2
icon_theme=Papirus-Dark
color_scheme_path=
custom_palette=false
standard_dialogs=default

[Fonts]
fixed="JetBrains Mono,10,-1,5,50,0,0,0,0,0"
general="Noto Sans,10,-1,5,50,0,0,0,0,0"
